language: android
android:
  components:
    - build-tools-21.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build
